/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projects;

import com.sun.glass.events.KeyEvent;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author san
 */
public class CreateAccount extends javax.swing.JFrame {

    Connection con=null;
    Statement st=null;
    AdminHome ah;
    /**
     * Creates new form CreateAccount
     */
    public CreateAccount()
    {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public CreateAccount(AdminHome ah) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.ah = ah;
        cpasswordError.setVisible(false);
        nameError.setVisible(false);
        contactError.setVisible(false);
        genderError.setVisible(false);
        emailError.setVisible(false);
        unameError.setVisible(false);
        passwordError.setVisible(false);
        dobError.setVisible(false);
        validemailError.setVisible(false);
        subjecterror.setVisible(false);
        validcontactError.setVisible(false);
        validusernameError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        uemail = new javax.swing.JTextField();
        upass = new javax.swing.JPasswordField();
        ucpass = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        ucontact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cpasswordError = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        nameError = new javax.swing.JLabel();
        contactError = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        emailError = new javax.swing.JLabel();
        unameError = new javax.swing.JLabel();
        passwordError = new javax.swing.JLabel();
        genderError = new javax.swing.JLabel();
        dobError = new javax.swing.JLabel();
        validemailError = new javax.swing.JLabel();
        validcontactError = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        validusernameError = new javax.swing.JLabel();
        subject = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        subjecterror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CreateAccount");
        setLocation(new java.awt.Point(540, 300));
        setPreferredSize(new java.awt.Dimension(600, 900));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Teacher");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Email :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Username :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Password :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Confirm Password :");

        fname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        uname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        uname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unameKeyTyped(evt);
            }
        });

        uemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uemailKeyTyped(evt);
            }
        });

        upass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ucpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        submit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        submit.setText("Create");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        ucontact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ucontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ucontactKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Contact :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("DOB :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Gender :");

        cpasswordError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cpasswordError.setForeground(new java.awt.Color(255, 0, 51));
        cpasswordError.setText("*Password did not match");

        gender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gender", "male", "female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        nameError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameError.setForeground(new java.awt.Color(255, 0, 51));
        nameError.setText("*enter name");

        contactError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactError.setForeground(new java.awt.Color(255, 0, 51));
        contactError.setText("*enter contact");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        emailError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailError.setForeground(new java.awt.Color(255, 0, 51));
        emailError.setText("*enter email");

        unameError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        unameError.setForeground(new java.awt.Color(255, 0, 51));
        unameError.setText("*enter username");

        passwordError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordError.setForeground(new java.awt.Color(255, 0, 51));
        passwordError.setText("*enter password");

        genderError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderError.setForeground(new java.awt.Color(255, 0, 51));
        genderError.setText("*select gender");

        dobError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dobError.setForeground(new java.awt.Color(255, 0, 51));
        dobError.setText("*enter DOB");

        validemailError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validemailError.setForeground(new java.awt.Color(255, 0, 51));
        validemailError.setText("*enter  a valid email");

        validcontactError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validcontactError.setForeground(new java.awt.Color(255, 0, 51));
        validcontactError.setText("*enter a valid contact number");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/back-icon.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        validusernameError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validusernameError.setForeground(new java.awt.Color(255, 0, 51));
        validusernameError.setText("*Error (starts with alphabet only)");

        subject.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "subject", "computer graphics", "human computer interaction", "system analysis and design", "unix" }));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Subject :");

        subjecterror.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subjecterror.setForeground(new java.awt.Color(255, 0, 51));
        subjecterror.setText("*select subject");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel11))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contactError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dobError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fname)
                                    .addComponent(ucontact)
                                    .addComponent(jTextField1)
                                    .addComponent(uemail)
                                    .addComponent(nameError)
                                    .addComponent(validcontactError, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(genderError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(validemailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subjecterror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(passwordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ucpass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(uname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upass, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unameError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(validusernameError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cpasswordError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(nameError)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ucontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validcontactError)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dobError)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genderError)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validemailError)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjecterror, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validusernameError)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordError)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ucpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpasswordError)
                .addGap(20, 20, 20)
                .addComponent(submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(21, 21, 21))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String name = fname.getText();
        String contact = ucontact.getText();
        String email = uemail.getText();
        String gen = gender.getSelectedItem().toString();
        String sub = subject.getSelectedItem().toString();
        /*if(gender.getSelectedItem().toString().contentEquals("gender"))
        {
            JOptionPane.showMessageDialog(rootPane,"select a gender");
        }
        else
        {
            String gen = gender.getSelectedItem().toString();
            System.out.println(gen);
        }*/
        String username = uname.getText();
        char pass[] = upass.getPassword();
        String password = new String(pass);
        char cpass[] = ucpass.getPassword();
        String cpassword = new String(cpass);
        Connection con = null;
        Statement st = null;
        /*if(username!=null && !password.trim().equals("")&& contact!=null && cpassword!=null && !username.trim().equals("") && email!=null && name!=null)
        {*/
            if(name!=null && !name.trim().equals(""))
            {
                if(contact!=null && !contact.trim().equals(""))
                {
                    if(contact.length()==10)
                    {
                    if(!gender.getSelectedItem().toString().contentEquals("gender"))
                    {
                        if(email!=null && !email.trim().equals(""))
                        {
                            if(email.contains("@") && email.endsWith(".com"))
                            {
                            if(!subject.getSelectedItem().toString().contentEquals("subject"))
                            {
                            if(username!=null && !username.trim().equals(""))
                            {
                                if(Character.isAlphabetic(username.charAt(0)))
                                {
                                if(password!=null && !password.trim().equals(""))
                                {
                                    if(password.equals(cpassword))
                                    {
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            //System.out.println("Driver Loaded");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizza","root","");
            //System.out.println("Connected");

            st = con.createStatement();
            String query = "INSERT INTO createtable values('"+username+"','"+name+"','"+password+"','"+email+"','"+sub+"','"+contact+"','"+gen+"')";

            int i = st.executeUpdate(query);

            if(i>0)
            {
                JOptionPane.showMessageDialog(new JFrame(), "Teacher is added successfully!");
            }
            else
            {
                Frame f = new Frame();
                JOptionPane.showMessageDialog(f, "There is a problem in adding teacher\nTry again..!");
            }
            con.close();
            ah.setVisible(true);
            this.setVisible(false);
        } 
        catch (ClassNotFoundException e) 
        {
            System.out.println(e);
        } 
        catch (SQLException e) 
        {
            System.out.println(e);
        }
                                       }
                                        else
                                        {
                                            cpasswordError.setVisible(true);
                                            passwordError.setVisible(false);
                                            emailError.setVisible(false);
                                            genderError.setVisible(false);
                                            contactError.setVisible(false);
                                            nameError.setVisible(false);
                                            unameError.setVisible(false);
                                            validcontactError.setVisible(false);
                                            validemailError.setVisible(false);
                                            validusernameError.setVisible(false);
                                        }
                                }
                                else
                                {
                                    passwordError.setVisible(true);
                                    emailError.setVisible(false);
                                    genderError.setVisible(false);
                                    contactError.setVisible(false);
                                    nameError.setVisible(false);
                                    cpasswordError.setVisible(false);
                                    unameError.setVisible(false);
                                    validemailError.setVisible(false);
                                    validcontactError.setVisible(false);
                                    validusernameError.setVisible(false);
                                }
                            }
                                else
                                {
                                    validusernameError.setVisible(true);
                                    passwordError.setVisible(false);
                                    emailError.setVisible(false);
                                    genderError.setVisible(false);
                                    contactError.setVisible(false);
                                    nameError.setVisible(false);
                                    cpasswordError.setVisible(false);
                                    unameError.setVisible(false);
                                    validemailError.setVisible(false);
                                    validcontactError.setVisible(false);
                                }
                            }
                            else
                            {
                                unameError.setVisible(true);
                                emailError.setVisible(false);
                                genderError.setVisible(false);
                                contactError.setVisible(false);
                                nameError.setVisible(false);
                                cpasswordError.setVisible(false);
                                passwordError.setVisible(false);
                                validemailError.setVisible(false);
                                validcontactError.setVisible(false);
                                validusernameError.setVisible(false);
                            }
                            }
                            else
                            {
                                subjecterror.setVisible(true);
                                unameError.setVisible(false);
                                emailError.setVisible(false);
                                genderError.setVisible(false);
                                contactError.setVisible(false);
                                nameError.setVisible(false);
                                cpasswordError.setVisible(false);
                                passwordError.setVisible(false);
                                validemailError.setVisible(false);
                                validcontactError.setVisible(false);
                                validusernameError.setVisible(false);
                            }
                            }
                            else
                            {
                                validemailError.setVisible(true);
                                emailError.setVisible(false);
                                genderError.setVisible(false);
                                contactError.setVisible(false);
                                nameError.setVisible(false);
                                cpasswordError.setVisible(false);
                                unameError.setVisible(false);
                                passwordError.setVisible(false);
                                validcontactError.setVisible(false);
                                validusernameError.setVisible(false);
                            }
                        }
                        else
                        {
                            emailError.setVisible(true);
                            genderError.setVisible(false);
                            contactError.setVisible(false);
                            nameError.setVisible(false);
                            cpasswordError.setVisible(false);
                            unameError.setVisible(false);
                            passwordError.setVisible(false);
                            validcontactError.setVisible(false);
                            validemailError.setVisible(false);
                            validusernameError.setVisible(false);
                        }
                    }
                    else
                    {
                        genderError.setVisible(true);
                        contactError.setVisible(false);
                        nameError.setVisible(false);
                        cpasswordError.setVisible(false);
                        emailError.setVisible(false);
                        unameError.setVisible(false);
                        passwordError.setVisible(false);
                        validemailError.setVisible(false);
                        validcontactError.setVisible(false);
                        validusernameError.setVisible(false);
                    }
                }
                    else
                    {
                        validcontactError.setVisible(true);
                        genderError.setVisible(false);
                        contactError.setVisible(false);
                        nameError.setVisible(false);
                        cpasswordError.setVisible(false);
                        emailError.setVisible(false);
                        unameError.setVisible(false);
                        passwordError.setVisible(false);
                        validemailError.setVisible(false);
                        validusernameError.setVisible(false);
                    }
                }
                else
                {
                    contactError.setVisible(true);
                    nameError.setVisible(false);
                    cpasswordError.setVisible(false);
                    genderError.setVisible(false);
                    emailError.setVisible(false);
                    unameError.setVisible(false);
                    passwordError.setVisible(false);
                    validemailError.setVisible(false);
                    validcontactError.setVisible(false);
                    validusernameError.setVisible(false);
                    
                }
            }
            else
            {
                nameError.setVisible(true);
                cpasswordError.setVisible(false);
                contactError.setVisible(false);
                genderError.setVisible(false);
                emailError.setVisible(false);
                unameError.setVisible(false);
                passwordError.setVisible(false);
                validemailError.setVisible(false);
                validcontactError.setVisible(false);
                validusernameError.setVisible(false);
            }
    }//GEN-LAST:event_submitActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed

    }//GEN-LAST:event_unameActionPerformed

    private void unameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameKeyTyped
        int ch = evt.getKeyChar();
        if(Character.isWhitespace(ch) || Character.isUpperCase(ch) || (!Character.isAlphabetic(ch) && !(ch==java.awt.event.KeyEvent.VK_BACK_SPACE) && !(ch==java.awt.event.KeyEvent.VK_DELETE) && ch!='.' && ch!='_'))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_unameKeyTyped

    private void ucontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ucontactKeyTyped
        int ch = evt.getKeyChar();
        if(!(Character.isDigit(ch) || (ch==KeyEvent.VK_BACKSPACE) || ch==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(ucontact.getText().length()==10)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_ucontactKeyTyped

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        ah.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void uemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uemailKeyTyped
        int ch = evt.getKeyChar();
        if(Character.isWhitespace(ch) || Character.isUpperCase(ch))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_uemailKeyTyped

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel contactError;
    private javax.swing.JLabel cpasswordError;
    private javax.swing.JLabel dobError;
    private javax.swing.JLabel emailError;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel genderError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nameError;
    private javax.swing.JLabel passwordError;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JLabel subjecterror;
    private javax.swing.JButton submit;
    private javax.swing.JTextField ucontact;
    private javax.swing.JPasswordField ucpass;
    private javax.swing.JTextField uemail;
    private javax.swing.JTextField uname;
    private javax.swing.JLabel unameError;
    private javax.swing.JPasswordField upass;
    private javax.swing.JLabel validcontactError;
    private javax.swing.JLabel validemailError;
    private javax.swing.JLabel validusernameError;
    // End of variables declaration//GEN-END:variables
}
