/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projects;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class PreviousTest extends javax.swing.JFrame {

    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    int size;
    boolean online;
    String tab[][];
    String username,testname,subject;
    
    /**
     * Creates new form ViewPreviousTest
     */
    public PreviousTest() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public PreviousTest(String testname,String username,String subject,boolean online) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.testname = testname;
        testName.setText(testname);
        this.username = username;
        this.subject = subject;
        this.online = online;
        show_test();
    }
    
    public ArrayList<User> test()
    {
        ArrayList<User> test = new ArrayList<>();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            //System.out.println("Driver Loaded");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizza","root","");
            //System.out.println("Connected");

            st = con.createStatement();
            String query = "SELECT * FROM `"+subject+"`.`"+testname+"`";
            rs = st.executeQuery(query);
            User user;
            while(rs.next())
            {
                user = new User(rs.getInt("Q_No"),rs.getString("Question"),rs.getString("option1"),rs.getString("option2"),rs.getString("option3"),rs.getString("option4"),rs.getString("correct"));
                test.add(user);
            }
            con.close();
        }
        catch (ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        return test;
    }
    
    public void show_test()
    {
        //table1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        ArrayList<User> list = test();
        size = list.size();
        tab = new String[size][7];
        DefaultTableModel model = (DefaultTableModel)table1.getModel();
        Object[] row = new Object[7];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getQuestionNo();
            row[1]=list.get(i).getQuestion();
            row[2]=list.get(i).getOption1();
            row[3]=list.get(i).getOption2();
            row[4]=list.get(i).getOption3();
            row[5]=list.get(i).getOption4();
            row[6]=list.get(i).getCorrect();
            model.addRow(row);
        }
        for(int r=0;r<size;r++)
        {
            for(int c=0;c<7;c++)
            {
                tab[r][c] = table1.getModel().getValueAt(r, c).toString();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        Update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        testName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(540, 300));
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Q.No", "Question", "option1", "option2", "option3", "option4", "correct"
            }
        ));
        table1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table1);

        Update.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/back-icon.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        testName.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        testName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        testName.setText("Test Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Update))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Update)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        for(int r=0;r<size;r++)
        {
            for(int c=0;c<7;c++)
            {
                String value = table1.getModel().getValueAt(r, c).toString();
                if(!value.equals(tab[r][c]))
                {
                    tab[r][c] = value;
                    
                    try
                    {
                        Class.forName("com.mysql.jdbc.Driver");

                        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizza","root","");

                        st = con.createStatement();
                        String query = "UPDATE `"+subject+"`.`"+testname+"` SET `Q_No`='"+table1.getModel().getValueAt(r, 0).toString()+"',"+
                                "`Question`='"+table1.getModel().getValueAt(r, 1).toString()+"',"+
                                "`option1`='"+table1.getModel().getValueAt(r, 2).toString()+"',"+
                                "`option2`='"+table1.getModel().getValueAt(r, 3).toString()+"',"+
                                "`option3`='"+table1.getModel().getValueAt(r, 4).toString()+"',"+
                                "`option4`='"+table1.getModel().getValueAt(r, 5).toString()+"',"+
                                "`correct`='"+table1.getModel().getValueAt(r, 6).toString()+"'"+" WHERE `Q_No`='"+table1.getModel().getValueAt(r, 0).toString()+"'";
                        
                        st.executeUpdate(query);
                        con.close();
                        if(online)
                            new ViewPreviousTest(username,subject,true).setVisible(true);
                        else
                            new ViewPreviousTest(username,subject,false).setVisible(true);
                        this.setVisible(false);
                    }
                    catch (ClassNotFoundException e)
                    {
                        System.out.println(e);
                    }
                    catch(SQLException e)
                    {
                        System.out.println(e);
                        JFrame f = new JFrame();
                        JOptionPane.showMessageDialog(f, "Could Not Update");
                    }
                }
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        if(online)
            new ViewPreviousTest(username,subject,true).setVisible(true);
        else
            new ViewPreviousTest(username,subject,false).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviousTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviousTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviousTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviousTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviousTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JButton back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    private javax.swing.JLabel testName;
    // End of variables declaration//GEN-END:variables
}
