/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projects;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Profile extends javax.swing.JFrame {
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    String username,subject;
    String name,contact,email,password,gender;
    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public Profile(String username,String subject)
    {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        validusernameError.setVisible(false);
        validcontactError.setVisible(false);
        validemailError.setVisible(false);
        this.username = username;
        this.subject = subject;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quizza", "root", "");
            
            st = con.createStatement();
            
            String query = "Select * FROM `quizza`.`createtable` WHERE username='"+username+"'";
            rs = st.executeQuery(query);
            if(rs.next())
            {
                
                name = rs.getString(2);
                    hellouser.setText("Hello "+name);
                    editusername.setText(username);
                    editusername.setEnabled(false);
                contact = rs.getString(6);
                    editcontact.setText(contact);
                    editcontact.setEnabled(false);
                email = rs.getString(4);
                    editemail.setText(email);
                    editemail.setEnabled(false);
                password = rs.getString(3);
                gender = rs.getString(7);
            }
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editusername = new javax.swing.JTextField();
        Ueditbtn = new javax.swing.JButton();
        Ceditbtn = new javax.swing.JButton();
        editcontact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        validusernameError = new javax.swing.JLabel();
        validcontactError = new javax.swing.JLabel();
        validemailError = new javax.swing.JLabel();
        editemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Eeditbtn = new javax.swing.JButton();
        hellouser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(540, 300));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/back-icon.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("username :");

        editusername.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        editusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editusernameActionPerformed(evt);
            }
        });
        editusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editusernameKeyTyped(evt);
            }
        });

        Ueditbtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Ueditbtn.setText("Edit");
        Ueditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UeditbtnActionPerformed(evt);
            }
        });

        Ceditbtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Ceditbtn.setText("Edit");
        Ceditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeditbtnActionPerformed(evt);
            }
        });

        editcontact.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        editcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editcontactKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editcontactKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("contact :");

        validusernameError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validusernameError.setForeground(new java.awt.Color(255, 0, 51));
        validusernameError.setText("*enter a valid username");

        validcontactError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validcontactError.setForeground(new java.awt.Color(255, 0, 51));
        validcontactError.setText("*enter a valid contact");

        validemailError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validemailError.setForeground(new java.awt.Color(255, 0, 51));
        validemailError.setText("*enter a valid email");

        editemail.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        editemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editemailKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("email  :");

        Eeditbtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Eeditbtn.setText("Edit");
        Eeditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EeditbtnActionPerformed(evt);
            }
        });

        hellouser.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        hellouser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hellouser.setText("Hello Teacher");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(validusernameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editemail)
                    .addComponent(editcontact)
                    .addComponent(validcontactError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(validemailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editusername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ueditbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ceditbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eeditbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(hellouser, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(hellouser)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Ueditbtn))
                .addGap(4, 4, 4)
                .addComponent(validusernameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Ceditbtn))
                .addGap(4, 4, 4)
                .addComponent(validcontactError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Eeditbtn))
                .addGap(4, 4, 4)
                .addComponent(validemailError)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(80, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Intro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 36))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 600));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(77, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1256, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Home(username,subject).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void editusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editusernameActionPerformed

    private void UeditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UeditbtnActionPerformed
        if(Ueditbtn.getText().equals("Update"))
        {
            if(Character.isAlphabetic(editusername.getText().charAt(0)))
            {
                try{
                    String query = "UPDATE `quizza`.`createtable` SET `username`='"+editusername.getText()+"',"+
                                        "`name`='"+name+"',"+
                                        "`password`='"+password+"',"+
                                        "`email`='"+email+"',"+
                                        "`subject`='"+subject+"',"+
                                        "`contact`='"+contact+"',"+
                                        " `gender`='"+gender+"' WHERE `username`='"+username+"'";
                    st.executeUpdate(query);
                    username = editusername.getText();
                    new Profile(username,subject).setVisible(true);
                    this.setVisible(false);
                }
                catch(MySQLIntegrityConstraintViolationException e)
                {
                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f, "username already exists", "Error", JOptionPane.WARNING_MESSAGE);
                }
                catch(SQLException e)
                {
                    System.out.println(e);
                }
            }
            else
            {
                validusernameError.setVisible(true);
            }
        }
        if(Ueditbtn.getText().equals("Edit"))
        {
            editusername.setEnabled(true);
            Ueditbtn.setText("Update");
            Ueditbtn.setEnabled(false);
        }
    }//GEN-LAST:event_UeditbtnActionPerformed

    private void editusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editusernameKeyTyped
    }//GEN-LAST:event_editusernameKeyTyped

    private void editusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editusernameKeyReleased
        char ch = evt.getKeyChar();
        if(Character.isWhitespace(ch) || Character.isUpperCase(ch) || (!Character.isAlphabetic(ch) && !(ch==java.awt.event.KeyEvent.VK_BACK_SPACE) && !(ch==java.awt.event.KeyEvent.VK_DELETE) && ch!='.' && ch!='_'))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(!editusername.getText().equals(username) && !editusername.getText().trim().equals(""))
        {
            Ueditbtn.setEnabled(true);
        }
        else
        {
            Ueditbtn.setEnabled(false);
        }
        if(ch==KeyEvent.VK_ENTER)
        {
            Ueditbtn.doClick();
        }
    }//GEN-LAST:event_editusernameKeyReleased

    private void editcontactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editcontactKeyReleased
    }//GEN-LAST:event_editcontactKeyReleased

    private void CeditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeditbtnActionPerformed
        if(Ceditbtn.getText().equals("Update"))
        {
            char cont[] = editcontact.getText().toCharArray();
            boolean ctrue = false;
            for(char c : cont)
            {
                if(!Character.isDigit(c))
                {    
                    ctrue = true;
                    break;
                }
            }
            if(!ctrue)
            {
                try{
                    String query = "UPDATE `quizza`.`createtable` SET `username`='"+username+"',"+
                                        "`name`='"+name+"',"+
                                        "`password`='"+password+"',"+
                                        "`email`='"+email+"',"+
                                        "`subject`='"+subject+"',"+
                                        "`contact`='"+editcontact.getText()+"',"+
                                        " `gender`='"+gender+"' WHERE `username`='"+username+"'";
                    st.executeUpdate(query);
                    contact = editcontact.getText();
                    new Profile(username,subject).setVisible(true);
                    this.setVisible(false);
                }
                catch(SQLException e)
                {
                    System.out.println(e);
                }
            }
            else
            {
                validcontactError.setVisible(true);
            }
        }
        if(Ceditbtn.getText().equals("Edit"))
        {
            editcontact.setEnabled(true);
            Ceditbtn.setText("Update");
            Ceditbtn.setEnabled(false);
        }
    }//GEN-LAST:event_CeditbtnActionPerformed

    private void editcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editcontactKeyTyped
        char ch = evt.getKeyChar();
        if(ch==KeyEvent.VK_BACKSPACE || ch==KeyEvent.VK_DELETE || editcontact.getText().length()==10)
        {
            if(!editcontact.getText().equals(contact) && (editcontact.getText()).length()==10)
            {
                Ceditbtn.setEnabled(true);
            }
            else
                Ceditbtn.setEnabled(false);
        }
        else
        {
            if(!(editcontact.getText()+ch).equals(contact) && (editcontact.getText()+ch).length()==10)
            {
                Ceditbtn.setEnabled(true);
            }
            else
                Ceditbtn.setEnabled(false);
        }
        if(!(Character.isDigit(ch) || (ch==KeyEvent.VK_BACKSPACE) || ch==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(editcontact.getText().length()==10)
        {
            if(ch!=KeyEvent.VK_BACKSPACE || ch!=KeyEvent.VK_DELETE)
            {   
                getToolkit().beep();
                evt.consume();
            }
        }
        if(ch==KeyEvent.VK_ENTER)
        {
            Ceditbtn.doClick();
        }
    }//GEN-LAST:event_editcontactKeyTyped

    private void EeditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EeditbtnActionPerformed
        if(Eeditbtn.getText().equals("Update"))
        {
            if(editemail.getText().contains("@") && editemail.getText().endsWith(".com"))
            {
                try{
                    String query = "UPDATE `quizza`.`createtable` SET `username`='"+username+"',"+
                                        "`name`='"+name+"',"+
                                        "`password`='"+password+"',"+
                                        "`email`='"+editemail.getText()+"',"+
                                        "`subject`='"+subject+"',"+
                                        "`contact`='"+contact+"',"+
                                        " `gender`='"+gender+"' WHERE `username`='"+username+"'";
                    st.executeUpdate(query);
                    email = editemail.getText();
                    new Profile(username,subject).setVisible(true);
                    this.setVisible(false);
                }
                catch(SQLException e)
                {
                    System.out.println(e);
                }
            }
            else
            {
                validemailError.setVisible(true);
            }
        }
        if(Eeditbtn.getText().equals("Edit"))
        {
            editemail.setEnabled(true);
            Eeditbtn.setText("Update");
            Eeditbtn.setEnabled(false);
        }
    }//GEN-LAST:event_EeditbtnActionPerformed

    private void editemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editemailKeyReleased
        int ch = evt.getKeyChar();
        if(Character.isWhitespace(ch) || Character.isUpperCase(ch))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(!editemail.getText().equals(email) && !editemail.getText().trim().equals(""))
        {
            Eeditbtn.setEnabled(true);
        }
        else
        {
            Eeditbtn.setEnabled(false);
        }
        if(ch==KeyEvent.VK_ENTER)
        {
            Eeditbtn.doClick();
        }
    }//GEN-LAST:event_editemailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ceditbtn;
    private javax.swing.JButton Eeditbtn;
    private javax.swing.JButton Ueditbtn;
    private javax.swing.JButton back;
    private javax.swing.JTextField editcontact;
    private javax.swing.JTextField editemail;
    private javax.swing.JTextField editusername;
    private javax.swing.JLabel hellouser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel validcontactError;
    private javax.swing.JLabel validemailError;
    private javax.swing.JLabel validusernameError;
    // End of variables declaration//GEN-END:variables
}
