/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projects;

import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class ResultTest extends javax.swing.JFrame {
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    
    JTextField jf;
    JButton jb,back;
    String username,subject,testname;
    boolean result,online;
    String tab[][];
    int size;
    
    public ResultTest()
    {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public ResultTest(String testname,String username,String subject,boolean result,boolean online) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.username = username;
        this.subject = subject;
        this.testname = testname;
        this.online = online;
        this.result = result;
        testnamelabel.setText(testname);
        jf = new JTextField("Search Roll Number...");
        jb = new JButton("Search");
        back = new JButton("");
        addSearch();
        show_result();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resulttb = new javax.swing.JTable();
        testnamelabel = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        resulttb.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        resulttb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No.", "Date", "Marks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resulttb);
        if (resulttb.getColumnModel().getColumnCount() > 0) {
            resulttb.getColumnModel().getColumn(0).setResizable(false);
            resulttb.getColumnModel().getColumn(1).setResizable(false);
            resulttb.getColumnModel().getColumn(2).setResizable(false);
        }

        testnamelabel.setBackground(new java.awt.Color(0, 51, 153));
        testnamelabel.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        testnamelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        testnamelabel.setText("Testname");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(testnamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(testnamelabel)
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
        );

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addSearch()
    {
        back.setIcon(new ImageIcon(getClass().getResource("Go-back-icon.png")));
        back.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backActionPerformed(evt);
        }
        });
        jf.setFont(new java.awt.Font("Times New Roman", 0, 22));
        jf.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jf.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if(jf.getText().equals("Search Roll Number..."))
                {
                    jf.setForeground(new java.awt.Color(0, 0, 0));
                    jf.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if(jf.getText().trim().equals(""))
                {
                    jf.setForeground(new java.awt.Color(0, 204, 204));
                    jf.setText("Search Roll Number...");
                }
            }
        });
        jf.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                int ch = e.getKeyChar();
                if(ch==KeyEvent.VK_ENTER)
                {
                    jb.doClick();
                }
            }
            @Override
            public void keyPressed(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            @Override
            public void keyReleased(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        jb.setFont(new java.awt.Font("Times New Roman", 0, 22));
        menubar.add(back);
        menubar.add(jf);
        menubar.add(jb);
        jb.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbActionPerformed(evt);
        }
        });
    }
    public void backActionPerformed(java.awt.event.ActionEvent evt)
    {
        new ViewPreviousTest(username,subject,true,true).setVisible(true);
        this.setVisible(false);
    }
    public void jbActionPerformed(java.awt.event.ActionEvent evt)
    {
        String srchroll = jf.getText().toUpperCase();
        boolean strue = false;
        int i;
        for(i=0; i<size; i++)
        {
            if(srchroll.equals(tab[i][0]))
            {
                strue = true;
                break;
            }
        }
        if(strue)
        {
            resulttb.setRowSelectionInterval(i, i);
        }
        else
        {
            if(srchroll.equals("Search Roll Number..."))
                srchroll = "";
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Roll Number "+srchroll+" does not found!", "Oops", JOptionPane.OK_OPTION);
        }
    }
    
    public ArrayList<User> test()
    {
        String query;
        ArrayList<User> test = new ArrayList<>();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            //System.out.println("Driver Loaded");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentresult","root","");
            //System.out.println("Connected");

            st = con.createStatement();
            query = "SELECT * FROM `online_"+testname+"`";
            rs = st.executeQuery(query);
            User user;
            
                while(rs.next())
                {
                    user = new User(rs.getString("rollNo"),rs.getString("date"),rs.getInt("marks"));
                    test.add(user);
                }
            con.close();
        }
        catch (ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        return test;
    }
    
    public void show_result()
    {
        //table2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        ArrayList<User> list = test();
        size = list.size();
        Object[] row;
        DefaultTableModel model = (DefaultTableModel)resulttb.getModel();
        
            tab = new String[size][3];
            row = new Object[3];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getRollNo();
            row[1]=list.get(i).getDate();
            row[2]=list.get(i).getMarks();
            //if(online)
              //  row[2]=list.get(i).getTestPass();
            model.addRow(row);
        }
        
            for(int r=0;r<size;r++)
            {
                for(int c=0;c<3;c++)
                {
                    tab[r][c] = resulttb.getModel().getValueAt(r, c).toString();
                }
            }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JTable resulttb;
    private javax.swing.JLabel testnamelabel;
    // End of variables declaration//GEN-END:variables
}
