/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projects;

import com.sun.glass.events.KeyEvent;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class StudentCreateAccount extends javax.swing.JFrame {

    AdminHome ah;
    
    public StudentCreateAccount() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public StudentCreateAccount(AdminHome ah) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.ah = ah;
        cpasswordError.setVisible(false);
        nameError.setVisible(false);
        contactError.setVisible(false);
        genderError.setVisible(false);
        emailError.setVisible(false);
        urollError.setVisible(false);
        passwordError.setVisible(false);
        dobError.setVisible(false);
        validemailError.setVisible(false);
        validcontactError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        uemail = new javax.swing.JTextField();
        upass = new javax.swing.JPasswordField();
        ucpass = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        ucontact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cpasswordError = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        nameError = new javax.swing.JLabel();
        contactError = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        emailError = new javax.swing.JLabel();
        urollError = new javax.swing.JLabel();
        passwordError = new javax.swing.JLabel();
        genderError = new javax.swing.JLabel();
        dobError = new javax.swing.JLabel();
        validemailError = new javax.swing.JLabel();
        validcontactError = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(540, 300));
        setPreferredSize(new java.awt.Dimension(600, 800));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Student");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Email :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Roll No. :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Password :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Confirm Password :");

        fname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        roll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        roll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rollKeyTyped(evt);
            }
        });

        uemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        upass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ucpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        submit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        submit.setText("Create");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        ucontact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ucontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ucontactKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Contact :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("DOB :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Gender :");

        cpasswordError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cpasswordError.setForeground(new java.awt.Color(255, 0, 51));
        cpasswordError.setText("*Password did not match");

        gender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gender", "male", "female" }));

        nameError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameError.setForeground(new java.awt.Color(255, 0, 51));
        nameError.setText("*enter name");

        contactError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactError.setForeground(new java.awt.Color(255, 0, 51));
        contactError.setText("*enter contact");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        emailError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailError.setForeground(new java.awt.Color(255, 0, 51));
        emailError.setText("*enter email");

        urollError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        urollError.setForeground(new java.awt.Color(255, 0, 51));
        urollError.setText("*enter Roll No.");

        passwordError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordError.setForeground(new java.awt.Color(255, 0, 51));
        passwordError.setText("*enter password");

        genderError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderError.setForeground(new java.awt.Color(255, 0, 51));
        genderError.setText("*select gender");

        dobError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dobError.setForeground(new java.awt.Color(255, 0, 51));
        dobError.setText("*enter DOB");

        validemailError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        validemailError.setForeground(new java.awt.Color(255, 0, 51));
        validemailError.setText("*enter  a valid email");

        validcontactError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        validcontactError.setForeground(new java.awt.Color(255, 0, 51));
        validcontactError.setText("*enter a valid contact number");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projects/back-icon.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(submit)
                                            .addComponent(ucpass, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                            .addComponent(ucontact)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                            .addComponent(uemail)
                                            .addComponent(roll)
                                            .addComponent(upass)
                                            .addComponent(validemailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(contactError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(validcontactError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dobError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(genderError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(emailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(urollError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(passwordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cpasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(nameError)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ucontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(7, 7, 7)
                        .addComponent(contactError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validcontactError)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(7, 7, 7)
                        .addComponent(dobError)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(7, 7, 7)
                        .addComponent(genderError)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(uemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(emailError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validemailError)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(7, 7, 7)
                        .addComponent(urollError)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(upass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7)
                        .addComponent(passwordError)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ucpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(7, 7, 7)
                        .addComponent(cpasswordError)
                        .addGap(20, 20, 20)
                        .addComponent(submit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed

    }//GEN-LAST:event_rollActionPerformed

    private void rollKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollKeyTyped
        /*int ch = evt.getKeyChar();
        if(Character.isWhitespace(ch) || Character.isUpperCase(ch) || (!Character.isAlphabetic(ch) && !(ch==java.awt.event.KeyEvent.VK_BACK_SPACE) && !(ch==java.awt.event.KeyEvent.VK_DELETE) && ch!='.' && ch!='_'))
        {
            getToolkit().beep();
            evt.consume();
        }*/
    }//GEN-LAST:event_rollKeyTyped

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String name = fname.getText();
        String contact = ucontact.getText();
        String email = uemail.getText().toLowerCase();
        String gen = gender.getSelectedItem().toString();
        /*if(gender.getSelectedItem().toString().contentEquals("gender"))
        {
            JOptionPane.showMessageDialog(rootPane,"select a gender");
        }
        else
        {
            String gen = gender.getSelectedItem().toString();
            System.out.println(gen);
        }*/
        String rollNo = roll.getText().toUpperCase();
        char pass[] = upass.getPassword();
        String password = new String(pass);
        char cpass[] = ucpass.getPassword();
        String cpassword = new String(cpass);
        Connection con = null;
        Statement st = null;
        /*if(username!=null && !password.trim().equals("")&& contact!=null && cpassword!=null && !username.trim().equals("") && email!=null && name!=null)
        {*/
            if(name!=null && !name.trim().equals(""))
            {
                if(contact!=null && !contact.trim().equals(""))
                {
                    if(contact.length()==10)
                    {
                        if(!gender.getSelectedItem().toString().contentEquals("gender"))
                        {
                            if(email!=null && !email.trim().equals(""))
                            {
                                if(email.contains("@") && email.endsWith(".com"))
                                {
                                    if(rollNo!=null && !rollNo.trim().equals(""))
                                    {
                                            if(password!=null && !password.trim().equals(""))
                                            {
                                                if(password.equals(cpassword))
                                                {
                                                    try
                                                    {
                                                        Class.forName("com.mysql.jdbc.Driver");
                                                        //System.out.println("Driver Loaded");

                                                        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentresult","root","");
                                                        //System.out.println("Connected");

                                                        st = con.createStatement();
                                                        String query = "INSERT INTO createtable values('"+rollNo+"','"+name+"','"+password+"','"+email+"','"+contact+"','"+gen+"')";

                                                        int i = st.executeUpdate(query);

                                                        if(i>0)
                                                        {
                                                            Frame f = new Frame();
                                                            JOptionPane.showMessageDialog(f, "Student is added successfully!");
                                                        }
                                                        else
                                                        {
                                                            Frame f = new Frame();
                                                            JOptionPane.showMessageDialog(f, "There is a problem in adding Student\nTry again..!");
                                                        }
                                                        con.close();
                                                        ah.setVisible(true);
                                                        this.setVisible(false);
                                                    }
                                                    catch (ClassNotFoundException e)
                                                    {
                                                        System.out.println(e);
                                                    }
                                                    catch (SQLException e)
                                                    {
                                                        System.out.println(e);
                                                    }
                                                }
                                                else
                                                {
                                                    cpasswordError.setVisible(true);
                                                    passwordError.setVisible(false);
                                                    emailError.setVisible(false);
                                                    genderError.setVisible(false);
                                                    contactError.setVisible(false);
                                                    nameError.setVisible(false);
                                                    urollError.setVisible(false);
                                                    validcontactError.setVisible(false);
                                                    validemailError.setVisible(false);
                                                }
                                            }
                                            else
                                            {
                                                passwordError.setVisible(true);
                                                emailError.setVisible(false);
                                                genderError.setVisible(false);
                                                contactError.setVisible(false);
                                                nameError.setVisible(false);
                                                cpasswordError.setVisible(false);
                                                urollError.setVisible(false);
                                                validemailError.setVisible(false);
                                                validcontactError.setVisible(false);
                                            }
                                    }
                                    else
                                    {
                                        urollError.setVisible(true);
                                        emailError.setVisible(false);
                                        genderError.setVisible(false);
                                        contactError.setVisible(false);
                                        nameError.setVisible(false);
                                        cpasswordError.setVisible(false);
                                        passwordError.setVisible(false);
                                        validemailError.setVisible(false);
                                        validcontactError.setVisible(false);
                                    }
                                }
                                else
                                {
                                    validemailError.setVisible(true);
                                    emailError.setVisible(false);
                                    genderError.setVisible(false);
                                    contactError.setVisible(false);
                                    nameError.setVisible(false);
                                    cpasswordError.setVisible(false);
                                    urollError.setVisible(false);
                                    passwordError.setVisible(false);
                                    validcontactError.setVisible(false);
                                }
                            }
                            else
                            {
                                emailError.setVisible(true);
                                genderError.setVisible(false);
                                contactError.setVisible(false);
                                nameError.setVisible(false);
                                cpasswordError.setVisible(false);
                                urollError.setVisible(false);
                                passwordError.setVisible(false);
                                validcontactError.setVisible(false);
                                validemailError.setVisible(false);
                            }
                        }
                        else
                        {
                            genderError.setVisible(true);
                            contactError.setVisible(false);
                            nameError.setVisible(false);
                            cpasswordError.setVisible(false);
                            emailError.setVisible(false);
                            urollError.setVisible(false);
                            passwordError.setVisible(false);
                            validemailError.setVisible(false);
                            validcontactError.setVisible(false);
                        }
                    }
                    else
                    {
                        validcontactError.setVisible(true);
                        genderError.setVisible(false);
                        contactError.setVisible(false);
                        nameError.setVisible(false);
                        cpasswordError.setVisible(false);
                        emailError.setVisible(false);
                        urollError.setVisible(false);
                        passwordError.setVisible(false);
                        validemailError.setVisible(false);
                    }
                }
                else
                {
                    contactError.setVisible(true);
                    nameError.setVisible(false);
                    cpasswordError.setVisible(false);
                    genderError.setVisible(false);
                    emailError.setVisible(false);
                    urollError.setVisible(false);
                    passwordError.setVisible(false);
                    validemailError.setVisible(false);
                    validcontactError.setVisible(false);

                }
            }
            else
            {
                nameError.setVisible(true);
                cpasswordError.setVisible(false);
                contactError.setVisible(false);
                genderError.setVisible(false);
                emailError.setVisible(false);
                urollError.setVisible(false);
                passwordError.setVisible(false);
                validemailError.setVisible(false);
                validcontactError.setVisible(false);
            }
    }//GEN-LAST:event_submitActionPerformed

    private void ucontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ucontactKeyTyped
        int ch = evt.getKeyChar();
        if(!(Character.isDigit(ch) || (ch==KeyEvent.VK_BACKSPACE) || ch==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(ucontact.getText().length()==10)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_ucontactKeyTyped

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        ah.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentCreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentCreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel contactError;
    private javax.swing.JLabel cpasswordError;
    private javax.swing.JLabel dobError;
    private javax.swing.JLabel emailError;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel genderError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nameError;
    private javax.swing.JLabel passwordError;
    private javax.swing.JTextField roll;
    private javax.swing.JButton submit;
    private javax.swing.JTextField ucontact;
    private javax.swing.JPasswordField ucpass;
    private javax.swing.JTextField uemail;
    private javax.swing.JPasswordField upass;
    private javax.swing.JLabel urollError;
    private javax.swing.JLabel validcontactError;
    private javax.swing.JLabel validemailError;
    // End of variables declaration//GEN-END:variables
}
